"""Add tables for web scraping

Revision ID: 660818444ba0
Revises: 6e7425b7c9de
Create Date: 2016-12-02 15:52:36.334162

"""
from alembic import op
import sqlalchemy as sa

import compranet


# revision identifiers, used by Alembic.
revision = '660818444ba0'
down_revision = '6e7425b7c9de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_web',
    sa.Column('ANUNCIO', sa.String(), nullable=False),
    sa.Column('CARACTER', sa.String(), nullable=True),
    sa.Column('CODIGO_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('FECHA_APERTURA_PROPOSICIONES', sa.String(), nullable=True),
    sa.Column('FORMA_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('NOMBRE_DE_LA_UC', sa.String(), nullable=True),
    sa.Column('NUMERO_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('PROC_F_PUBLICACION', sa.String(), nullable=True),
    sa.Column('TIPO_CONTRATACION', sa.String(), nullable=True),
    sa.Column('TITULO_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('_ANEXOS_CP', compranet.database.JSONEncodedObject(), nullable=True),
    sa.Column('_ANEXOS_OD', compranet.database.JSONEncodedObject(), nullable=True),
    sa.Column('_CORREO_DEL_OPERADOR', sa.String(), nullable=True),
    sa.Column('_CREDITO_EXTERNO', sa.String(), nullable=True),
    sa.Column('_DESC_ANUNCIO', sa.String(), nullable=True),
    sa.Column('_ENTIDAD_FEDERATIVA', sa.String(), nullable=True),
    sa.Column('_EXCLUSIVO_MIPYMES', sa.String(), nullable=True),
    sa.Column('_NOMBRE_DEL_OPERADOR', sa.String(), nullable=True),
    sa.Column('_NOTAS', sa.String(), nullable=True),
    sa.Column('_PROCEDIMIENTOS', compranet.database.JSONEncodedObject(), nullable=True),
    sa.Column('_UPDATED', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ANUNCIO')
    )
    op.create_table('contratos_web_hist',
    sa.Column('ANUNCIO', sa.String(), nullable=True),
    sa.Column('CARACTER', sa.String(), nullable=True),
    sa.Column('CODIGO_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('FECHA_APERTURA_PROPOSICIONES', sa.String(), nullable=True),
    sa.Column('FORMA_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('NOMBRE_DE_LA_UC', sa.String(), nullable=True),
    sa.Column('NUMERO_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('PROC_F_PUBLICACION', sa.String(), nullable=True),
    sa.Column('TIPO_CONTRATACION', sa.String(), nullable=True),
    sa.Column('TITULO_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('_ANEXOS_CP', compranet.database.JSONEncodedObject(), nullable=True),
    sa.Column('_ANEXOS_OD', compranet.database.JSONEncodedObject(), nullable=True),
    sa.Column('_CORREO_DEL_OPERADOR', sa.String(), nullable=True),
    sa.Column('_CREDITO_EXTERNO', sa.String(), nullable=True),
    sa.Column('_DESC_ANUNCIO', sa.String(), nullable=True),
    sa.Column('_ENTIDAD_FEDERATIVA', sa.String(), nullable=True),
    sa.Column('_EXCLUSIVO_MIPYMES', sa.String(), nullable=True),
    sa.Column('_NOMBRE_DEL_OPERADOR', sa.String(), nullable=True),
    sa.Column('_NOTAS', sa.String(), nullable=True),
    sa.Column('_PROCEDIMIENTOS', compranet.database.JSONEncodedObject(), nullable=True),
    sa.Column('_UPDATED', sa.DateTime(), nullable=True),
    sa.Column('_REMOVED', sa.Boolean(), nullable=True),
    sa.Column('_ID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contratos_web_hist')
    op.drop_table('contratos_web')
    # ### end Alembic commands ###
