"""Update xls models Oct 2016

Revision ID: 6e7425b7c9de
Revises: 8d3351e0a068
Create Date: 2016-11-29 18:39:50.339434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7425b7c9de'
down_revision = '8d3351e0a068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contratos_xls', sa.Column('C_EXTERNO', sa.Boolean(), nullable=True))
    op.add_column('contratos_xls', sa.Column('ORGANISMO', sa.String(), nullable=True))
    op.add_column('contratos_xls_hist', sa.Column('C_EXTERNO', sa.Boolean(), nullable=True))
    op.add_column('contratos_xls_hist', sa.Column('ORGANISMO', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos_xls_hist', 'ORGANISMO')
    op.drop_column('contratos_xls_hist', 'C_EXTERNO')
    op.drop_column('contratos_xls', 'ORGANISMO')
    op.drop_column('contratos_xls', 'C_EXTERNO')
    # ### end Alembic commands ###
