"""Base xls models Aug 2016

Revision ID: 8d3351e0a068
Revises: 
Create Date: 2016-11-29 16:46:54.366671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3351e0a068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_xls',
    sa.Column('GOBIERNO', sa.String(), nullable=True),
    sa.Column('SIGLAS', sa.String(), nullable=True),
    sa.Column('DEPENDENCIA', sa.String(), nullable=True),
    sa.Column('CLAVEUC', sa.String(), nullable=True),
    sa.Column('NOMBRE_DE_LA_UC', sa.String(), nullable=True),
    sa.Column('RESPONSABLE', sa.String(), nullable=True),
    sa.Column('CODIGO_EXPEDIENTE', sa.Integer(), nullable=True),
    sa.Column('TITULO_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('PLANTILLA_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('NUMERO_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('EXP_F_FALLO', sa.String(), nullable=True),
    sa.Column('PROC_F_PUBLICACION', sa.String(), nullable=True),
    sa.Column('FECHA_APERTURA_PROPOSICIONES', sa.String(), nullable=True),
    sa.Column('CARACTER', sa.String(), nullable=True),
    sa.Column('TIPO_CONTRATACION', sa.String(), nullable=True),
    sa.Column('TIPO_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('FORMA_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('CODIGO_CONTRATO', sa.Integer(), nullable=False),
    sa.Column('TITULO_CONTRATO', sa.String(), nullable=True),
    sa.Column('FECHA_INICIO', sa.String(), nullable=True),
    sa.Column('FECHA_FIN', sa.String(), nullable=True),
    sa.Column('IMPORTE_CONTRATO', sa.Float(), nullable=True),
    sa.Column('MONEDA', sa.String(), nullable=True),
    sa.Column('ESTATUS_CONTRATO', sa.String(), nullable=True),
    sa.Column('ARCHIVADO', sa.String(), nullable=True),
    sa.Column('CONVENIO_MODIFICATORIO', sa.Boolean(), nullable=True),
    sa.Column('RAMO', sa.String(), nullable=True),
    sa.Column('CLAVE_PROGRAMA', sa.String(), nullable=True),
    sa.Column('APORTACION_FEDERAL', sa.Float(), nullable=True),
    sa.Column('FECHA_CELEBRACION', sa.String(), nullable=True),
    sa.Column('CONTRATO_MARCO', sa.Boolean(), nullable=True),
    sa.Column('COMPRA_CONSOLIDADA', sa.Boolean(), nullable=True),
    sa.Column('PLURIANUAL', sa.Boolean(), nullable=True),
    sa.Column('CLAVE_CARTERA_SHCP', sa.String(), nullable=True),
    sa.Column('ESTRATIFICACION_MUC', sa.String(), nullable=True),
    sa.Column('FOLIO_RUPC', sa.Integer(), nullable=True),
    sa.Column('PROVEEDOR_CONTRATISTA', sa.String(), nullable=True),
    sa.Column('ESTRATIFICACION_MPC', sa.String(), nullable=True),
    sa.Column('SIGLAS_PAIS', sa.String(), nullable=True),
    sa.Column('ESTATUS_EMPRESA', sa.String(), nullable=True),
    sa.Column('CUENTA_ADMINISTRADA_POR', sa.String(), nullable=True),
    sa.Column('ANUNCIO', sa.String(), nullable=True),
    sa.Column('_SOURCE', sa.String(), nullable=False),
    sa.Column('_UPDATED', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('CODIGO_CONTRATO', '_SOURCE')
    )
    op.create_table('contratos_xls_hist',
    sa.Column('GOBIERNO', sa.String(), nullable=True),
    sa.Column('SIGLAS', sa.String(), nullable=True),
    sa.Column('DEPENDENCIA', sa.String(), nullable=True),
    sa.Column('CLAVEUC', sa.String(), nullable=True),
    sa.Column('NOMBRE_DE_LA_UC', sa.String(), nullable=True),
    sa.Column('RESPONSABLE', sa.String(), nullable=True),
    sa.Column('CODIGO_EXPEDIENTE', sa.Integer(), nullable=True),
    sa.Column('TITULO_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('PLANTILLA_EXPEDIENTE', sa.String(), nullable=True),
    sa.Column('NUMERO_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('EXP_F_FALLO', sa.String(), nullable=True),
    sa.Column('PROC_F_PUBLICACION', sa.String(), nullable=True),
    sa.Column('FECHA_APERTURA_PROPOSICIONES', sa.String(), nullable=True),
    sa.Column('CARACTER', sa.String(), nullable=True),
    sa.Column('TIPO_CONTRATACION', sa.String(), nullable=True),
    sa.Column('TIPO_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('FORMA_PROCEDIMIENTO', sa.String(), nullable=True),
    sa.Column('CODIGO_CONTRATO', sa.Integer(), nullable=True),
    sa.Column('TITULO_CONTRATO', sa.String(), nullable=True),
    sa.Column('FECHA_INICIO', sa.String(), nullable=True),
    sa.Column('FECHA_FIN', sa.String(), nullable=True),
    sa.Column('IMPORTE_CONTRATO', sa.Float(), nullable=True),
    sa.Column('MONEDA', sa.String(), nullable=True),
    sa.Column('ESTATUS_CONTRATO', sa.String(), nullable=True),
    sa.Column('ARCHIVADO', sa.String(), nullable=True),
    sa.Column('CONVENIO_MODIFICATORIO', sa.Boolean(), nullable=True),
    sa.Column('RAMO', sa.String(), nullable=True),
    sa.Column('CLAVE_PROGRAMA', sa.String(), nullable=True),
    sa.Column('APORTACION_FEDERAL', sa.Float(), nullable=True),
    sa.Column('FECHA_CELEBRACION', sa.String(), nullable=True),
    sa.Column('CONTRATO_MARCO', sa.Boolean(), nullable=True),
    sa.Column('COMPRA_CONSOLIDADA', sa.Boolean(), nullable=True),
    sa.Column('PLURIANUAL', sa.Boolean(), nullable=True),
    sa.Column('CLAVE_CARTERA_SHCP', sa.String(), nullable=True),
    sa.Column('ESTRATIFICACION_MUC', sa.String(), nullable=True),
    sa.Column('FOLIO_RUPC', sa.Integer(), nullable=True),
    sa.Column('PROVEEDOR_CONTRATISTA', sa.String(), nullable=True),
    sa.Column('ESTRATIFICACION_MPC', sa.String(), nullable=True),
    sa.Column('SIGLAS_PAIS', sa.String(), nullable=True),
    sa.Column('ESTATUS_EMPRESA', sa.String(), nullable=True),
    sa.Column('CUENTA_ADMINISTRADA_POR', sa.String(), nullable=True),
    sa.Column('ANUNCIO', sa.String(), nullable=True),
    sa.Column('_SOURCE', sa.String(), nullable=True),
    sa.Column('_UPDATED', sa.DateTime(), nullable=True),
    sa.Column('_REMOVED', sa.Boolean(), nullable=True),
    sa.Column('_ID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_ID')
    )
    op.create_table('sources_xls',
    sa.Column('_SOURCE', sa.String(), nullable=False),
    sa.Column('_UPDATED', sa.DateTime(), nullable=False),
    sa.Column('SHA256', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_SOURCE', '_UPDATED')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources_xls')
    op.drop_table('contratos_xls_hist')
    op.drop_table('contratos_xls')
    # ### end Alembic commands ###
